### ISSUE TITLE
Cannot find daemon loader org/apache/commons/daemon/support/DaemonLoader

### ISSUE THREAD

**Issue by kiddyt00** [HashDataInc/bireme#101] opened 2018-04-11 04:42 UTC
Cannot find daemon loader org/apache/commons/daemon/support/DaemonLoader  how to slove this problem

**Comment by yxs1112003** [comment] 2018-07-31 10:46
Cannot find daemon loader org/apache/commons/daemon/support/DaemonLoader
Service exit with a return value of 1

is this question sloved?

**Comment by wangzw** [comment] 2018-08-02 01:47
Seems like org/apache/commons/daemon/support/DaemonLoader  is not in class path. How did you run the command?

**Comment by yxs1112003** [comment] 2018-08-02 02:34
Thanks for reply. 

I put commons-daemon-1.0.12.jar to $JAVA_HOME/lib/ and run 

bin/bireme start

But it seems does not work

and the errlog is
cat  logs/bireme.err
```python
Cannot find daemon loader org/apache/commons/daemon/support/DaemonLoader
Service exit with a return value of 1
```

**Comment by DavenAaron** [comment] 2018-09-11 10:08
I also have this problem. Is it fixed now?

**Comment by wangzw** [comment] 2018-09-11 10:14
Try use released binary. Which version of JDK are you using?

**Comment by DavenAaron** [comment] 2018-09-11 10:26
java version "1.8.0_181"

**Comment by DavenAaron** [comment] 2018-09-11 10:29
version: 1.0.0

单独下载 commons-daemon-1.0.15.jar 复制到$JAVA_HOME/lib 下 报错信息如下

java.lang.ClassNotFoundException: cn.hashdata.bireme.Bireme
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:148)
Cannot load daemon

**Comment by wangzw** [comment] 2018-09-11 11:53
bireme 的 jar 包不在路径里，直接下载编译好的bireme 包吧。https://github.com/HashDataInc/bireme/releases/download/v2.0.0-alpha-1/bireme-2.0.0-alpha-1.tar.gz

**Comment by DavenAaron** [comment] 2018-09-13 03:42
Greenplum table and MySQL table size are inconsistent!


这里的table size是指的临时表么？

**Comment by DavenAaron** [comment] 2018-09-13 09:45
这个问题已经解决

**Comment by DavenAaron** [comment] 2018-09-16 14:44
按照文档  提示如下：   望告知
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243)
Caused by: java.lang.NullPointerException
	at cn.hashdata.bireme.Bireme.getTableInfo(Bireme.java:111)
	at cn.hashdata.bireme.Bireme.start(Bireme.java:283)
	... 5 more
Cannot start daemon
Service exit with a return value of 5

**Comment by wangzw** [comment] 2018-09-16 14:50
> 按照文档 提示如下： 望告知
> java.lang.reflect.InvocationTargetException
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243)
> Caused by: java.lang.NullPointerException
> at cn.hashdata.bireme.Bireme.getTableInfo(Bireme.java:111)
> at cn.hashdata.bireme.Bireme.start(Bireme.java:283)
> ... 5 more
> Cannot start daemon
> Service exit with a return value of 5

Please file a new issue.

**Closed by wangzw** 2018-09-16 14:50 UTC
